{% set name = "cotengra" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cotengra-{{ version }}.tar.gz
  sha256: 89a01d1d0e025cb6a477fafc318955859067c17c67562de933340c7506c453d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - autoray
    - cytoolz
    - optuna
    - tqdm

test:
  imports:
    - cotengra
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://cotengra.readthedocs.io/
  summary: Hyper optimized contraction trees for large tensor networks and einsums.
  dev_url: https://github.com/jcmgray/cotengra/
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jcmgray
