{% set name = "cotengra" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cotengra-{{ version }}.tar.gz
  sha256: 20855f87c1df6534dd1dad17302ad3a5dcc88a86e38a9ce93117b24545dc38cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - autoray
    - cytoolz
    - optuna
    - tqdm

test:
  imports:
    - cotengra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jcmgray/cotengra
  summary: Hyper optimized contraction trees for large tensor networks and einsums.
  dev_url: https://github.com/jcmgray/cotengra/
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jcmgray
