{% set name = "cotengra" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cotengra-{{ version }}.tar.gz
  sha256: a56b921d0339d1397e925a7b69029d3301636d09b99b509368751753bda39d24

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - autoray
    - cytoolz
    - optuna
    - tqdm

test:
  imports:
    - cotengra
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://cotengra.readthedocs.io/
  summary: Hyper optimized contraction trees for large tensor networks and einsums.
  dev_url: https://github.com/jcmgray/cotengra/
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jcmgray
